name: azure preview www

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'apps/www/**'
      - 'internal/components/**'
      - './github/workflows/azure-preview-www.yml'
      - './github/workflows/azure-deploy-www.yml'
      - 'Dockerfile'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  deploy-preview:
    uses: ./.github/workflows/azure-deploy-www.yml
    with:
      environment: preview
      pr_number: ${{ github.event.number }}
      update_comment: true
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
