name: deploy www to aca

on:
  workflow_dispatch:
  push:
    paths:
      - 'apps/www/**'
      - 'internal/components/**'

permissions:
  id-token: write   # needed for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: az login (oidc)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: acr login
        run: az acr login --name designsystemetacr

      - name: build & push (www)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: www
          platforms: linux/amd64
          push: true
          tags: designsystemetacr.azurecr.io/www:${{ github.sha }}

      - name: deploy
        uses: azure/container-apps-deploy-action@v1
        with:
          resourceGroup: rg-designsystemet-test
          containerAppName: www-test-ca-app
          containerAppEnvironment: www-test-ca
          acrName: designsystemetacr
          imageToDeploy: designsystemetacr.azurecr.io/www:${{ github.sha }}
          targetPort: 8000
          ingress: external
          environmentVariables: |
            PORT=8000
            HOST=0.0.0.0
